////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     ANTLR Version: 4.13.1
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// Generated from d:/EU4 Grammar/PDXLanguageParser.g4 by ANTLR 4.13.1

//// Unreachable code detected
//#pragma warning disable 0162
//// The variable '...' is assigned but its value is never used
//#pragma warning disable 0219
//// Missing XML comment for publicly visible type or member '...'
//#pragma warning disable 1591
//// Ambiguous reference in cref attribute
//#pragma warning disable 419

//using Antlr4.Runtime.Misc;
//using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
//using IToken = Antlr4.Runtime.IToken;

///// <summary>
///// This interface defines a complete listener for a parse tree produced by
///// <see cref="PDXLanguageParser"/>.
///// </summary>
//[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
//[System.CLSCompliant(false)]
//public interface IPDXLanguageParserListener : IParseTreeListener {
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.areaFile"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void EnterAreaFile([NotNull] PDXLanguageParser.AreaFileContext context);
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.areaFile"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void ExitAreaFile([NotNull] PDXLanguageParser.AreaFileContext context);
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.intList"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void EnterIntList([NotNull] PDXLanguageParser.IntListContext context);
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.intList"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void ExitIntList([NotNull] PDXLanguageParser.IntListContext context);
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.color"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void EnterColor([NotNull] PDXLanguageParser.ColorContext context);
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.color"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void ExitColor([NotNull] PDXLanguageParser.ColorContext context);
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.area"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void EnterArea([NotNull] PDXLanguageParser.AreaContext context);
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.area"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void ExitArea([NotNull] PDXLanguageParser.AreaContext context);
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.rpar"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void EnterRpar([NotNull] PDXLanguageParser.RparContext context);
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.rpar"/>.
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	void ExitRpar([NotNull] PDXLanguageParser.RparContext context);
//}
