////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     ANTLR Version: 4.13.1
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// Generated from d:/EU4 Grammar/PDXLanguageParser.g4 by ANTLR 4.13.1

//// Unreachable code detected
//#pragma warning disable 0162
//// The variable '...' is assigned but its value is never used
//#pragma warning disable 0219
//// Missing XML comment for publicly visible type or member '...'
//#pragma warning disable 1591
//// Ambiguous reference in cref attribute
//#pragma warning disable 419


//using Antlr4.Runtime.Misc;
//using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
//using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
//using IToken = Antlr4.Runtime.IToken;
//using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

///// <summary>
///// This class provides an empty implementation of <see cref="IPDXLanguageParserListener"/>,
///// which can be extended to create a listener which only needs to handle a subset
///// of the available methods.
///// </summary>
//[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
//[System.Diagnostics.DebuggerNonUserCode]
//[System.CLSCompliant(false)]
//public partial class PDXLanguageParserBaseListener : IPDXLanguageParserListener {
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.areaFile"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void EnterAreaFile([NotNull] PDXLanguageParser.AreaFileContext context) { }
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.areaFile"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void ExitAreaFile([NotNull] PDXLanguageParser.AreaFileContext context) { }
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.intList"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void EnterIntList([NotNull] PDXLanguageParser.IntListContext context) { }
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.intList"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void ExitIntList([NotNull] PDXLanguageParser.IntListContext context) { }
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.color"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void EnterColor([NotNull] PDXLanguageParser.ColorContext context) { }
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.color"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void ExitColor([NotNull] PDXLanguageParser.ColorContext context) { }
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.area"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void EnterArea([NotNull] PDXLanguageParser.AreaContext context) { }
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.area"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void ExitArea([NotNull] PDXLanguageParser.AreaContext context) { }
//	/// <summary>
//	/// Enter a parse tree produced by <see cref="PDXLanguageParser.rpar"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void EnterRpar([NotNull] PDXLanguageParser.RparContext context) { }
//	/// <summary>
//	/// Exit a parse tree produced by <see cref="PDXLanguageParser.rpar"/>.
//	/// <para>The default implementation does nothing.</para>
//	/// </summary>
//	/// <param name="context">The parse tree.</param>
//	public virtual void ExitRpar([NotNull] PDXLanguageParser.RparContext context) { }

//	/// <inheritdoc/>
//	/// <remarks>The default implementation does nothing.</remarks>
//	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
//	/// <inheritdoc/>
//	/// <remarks>The default implementation does nothing.</remarks>
//	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
//	/// <inheritdoc/>
//	/// <remarks>The default implementation does nothing.</remarks>
//	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
//	/// <inheritdoc/>
//	/// <remarks>The default implementation does nothing.</remarks>
//	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
//}
